### ISSUE TITLE
Collisions of doom

### ISSUE THREAD

**Issue by etray** [atomicham/breakpong#16]
If you let the balls bounce around, eventually they will stick together and hang there in midair.

**Comment by nazhrenn** [comment]
Oh man, that must be humorous to see! I'm wondering if we fix the collision detection/bounce code if it will resolve this issue.

**Comment by etray** [comment]
The bounce logic was the culprit. It seems to be in Ok shape now. Gives us a point to improve from. One thing that became apparent is that the physics loop needs to be able to keep up, Otherwise, we detect collisions too late, and things end up stuck inside one another. Added a method to detect if a point falls within a rectangle, which may be of use if we ever want to rework the overlap function.
